apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shortlet-current-time.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "shortlet-current-time.name" . }}
    helm.sh/chart: {{ include "shortlet-current-time.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "shortlet-current-time.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "shortlet-current-time.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
        updatedAt: {{ now | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: {{ .Chart.Name }}
            - name: NODE_ENV
              value: {{ .Values.app.node_env }}
            - name: PORT
              value: {{ .Values.app.port | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
