name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dependency-cache-${{ hashFiles('package.json') }}
          restore-keys: |
            dependency-cache-

      - name: Install dependencies
        working-directory: ./api
        run: yarn install

      - name: Build TypeScript
        working-directory: ./api
        run: yarn build:tsc

      - name: Persist workspace (node_modules and dist)
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: |
            node_modules
            dist

  test:
    runs-on: ubuntu-latest
    needs: build

    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version

      - name: Build and Run Docker Compose
        run: |
          set -o pipefail
          docker-compose up --build \
          --abort-on-container-exit \
          --exit-code-from app

  helm_lint: 
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Configure helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Lint charts
        working-directory: ./terraform/modules/app
        run: find . -path "./*" -type d -prune -not -name ".git" -not -name ".github" -not -name "docs" | xargs helm lint

  docker_build_push:
    runs-on: ubuntu-latest
    needs: helm_lint

    defaults:
      run:
        working-directory: ./api

    permissions:
      id-token: write 
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROV }}
          create_credentials_file: true
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}       
          token_format: "access_token"
          access_token_lifetime: "120s"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker for GCR
        run: gcloud auth configure-docker gcr.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up environment variables
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          APP_NAME: ${{ github.event.repository.name }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          NAME=${{ env.REGISTRY }}/${{ env.APP_NAME }}

          if [ "${{ env.GITHUB_REF_NAME }}" = "main" ]; then
            TAG="latest-${{ env.GITHUB_SHA }}"
          else
            TAG="${{ env.GITHUB_REF_NAME }}"
          fi

          IMG=${NAME}:${{ env.GITHUB_SHA }}
          LATEST=${NAME}:${TAG}

          echo "IMAGE=$IMG" >> $GITHUB_ENV
          echo "LATEST_IMAGE=$LATEST" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE }} .
          docker tag ${{ env.IMAGE }} ${{ env.LATEST_IMAGE }}

      - name: Push Docker image to GCR
        run: |
          docker push ${{ env.LATEST_IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker_build_push

    defaults:
      run:
        working-directory: ./terraform

    permissions:
      id-token: write 
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROV }}
          create_credentials_file: true
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}       
          token_format: "access_token"
          access_token_lifetime: "600s"
      
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5
          terraform_wrapper: true
             
      - name: Terraform init
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt -recursive -write=true 

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -var 'cluster_name=helios' -var 'project_id=${{ secrets.GCP_PROJECT_ID }}' -var 'network_project_id=${{ secrets.GCP_PROJECT_ID }}' -var 'image_repository=${{ secrets.REGISTRY }}/${{ env.APP_NAME }}' -var 'app_name=${{ env.APP_NAME }}' -var 'app_env=${{ env.APP_ENV }}' -var 'app_namsepace=${{ env.APP_NAMESPACE }}' -var-file="config/config.tfvars" -out="tfplan"
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply tfplan -auto-approve

      - name: Save Terraform output
        working-directory: ./terraform
        id: terraform_output
        run: echo "ingress_loadbalancer_ip=$(terraform output -raw ingress_loadbalancer_ip)" >> $GITHUB_ENV

  validate:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Await deployment
        run: sleep 60
      - name: Check deployment
        run: |
          curl --fail http://$INGRESS_LOADBALANCER_IP/time || exit 1
          